src/app/index.js
src/components/BaseView.js
src/components/Label.js
src/components/TextInput.js
src/components/index.js
src/schedule/ScheduleDetail.js
src/schedule/ScheduleList.js
src/schedule/ScheduleListCalendar.js

- Added PropTypes, styles to ScheduleList and ScheduleDetail
- Extracted a common component called Label.

Clean-up Schedule Components

---

package.json
scripts/jest/environment.js
src/api/__tests__/request-test.js
src/api/request.js

Axios uses xhr for making requests in react-native environments, which makes it a good fit for our api, since we need xhr for image uploads.

Use axios for api wrapper

---

package.json
src/api/__tests__/api-test.js
src/api/__tests__/parse-test.js
src/api/__tests__/request-test.js
src/auth/__tests__/actions-tests.js
src/auth/__tests__/reducers-test.js
src/components/Label/__tests__/Label-test.js
src/stores/__tests__/HTTPRequestMiddleware-test.js
src/stores/__tests__/contextMiddleware-test.js
src/stores/__tests__/helpers-test.js

Its getting in the way more than it is helping.

Disable jest's automocking

---

src/auth/Login.js
src/auth/__tests__/Login-test.js
src/auth/__tests__/__snapshots__/Login-test.js.snap
src/auth/__tests__/actions-tests.js
src/auth/__tests__/reducers-test.js
src/auth/actions.js
src/auth/reducer.js

At the moment we only handle bad auth detail login failures.

Handle unexpected errors on auth screen

---

package.json
src/config/dev.js
src/config/index.js
src/config/prd.js

We need to use `__DEV__` since react native sets `NODE_ENV` itself depending on its value.

Fix env configs

---

src/components/MultiLineTextInput/__tests__/MultiLineTextInput-test.js
src/components/MultiLineTextInput/__tests__/__snapshots__/MultiLineTextInput-test.js.snap
src/components/MultiLineTextInput/index.js
src/components/MultiLineTextInput/styles.js
src/components/TextInput/index.js
src/views/Landing/index.js
src/views/__tests__/__snapshots__/Login-test.js.snap

MultiLineTextInput Component

---

src/containers/OnboardingMotivationContainer.js
src/reducers/navigation.js
src/routes.js
src/views/OnboardingMotivation/__tests__/OnboardingOccupation-tests.js
src/views/OnboardingMotivation/__tests__/__snapshots__/OnboardingOccupation-tests.js.snap
src/views/OnboardingMotivation/index.js
src/views/OnboardingMotivation/styles.js

Onboarding: Motivation

---

src/containers/OnboardingThreeWordsContainer.js
src/routes.js
src/views/OnboardingThreeWords/__tests__/OnboardingThreeWords-tests.js
src/views/OnboardingThreeWords/__tests__/__snapshots__/OnboardingThreeWords-tests.js.snap
src/views/OnboardingThreeWords/index.js
src/views/OnboardingThreeWords/styles.js

I'll probably need to build a more robust "tag" component, but I don't have the bandwidth to do that right now, and it feels like something that'll take a lot of time, require a ton of testing, and doesn't really have very good value. 
But it may be a nice open source component. :D
@justinvdm Ready for review.

Onboarding: Three Words

---

src/containers/OnboardingSkillsContainer.js
src/reducers/navigation.js
src/routes.js
src/views/OnboardingSkills/__tests__/OnboardingSkills-tests.js
src/views/OnboardingSkills/__tests__/__snapshots__/OnboardingSkills-tests.js.snap
src/views/OnboardingSkills/index.js
src/views/OnboardingSkills/styles.js

Onboarding: Skills

---

src/api/__tests__/profiles-test.js
src/api/profiles.js

fix `isProfileComplete()`

---

src/views/Activity/__tests__/__snapshots__/Activity-test.js.snap
src/views/Activity/index.js
src/views/Activity/styles.js

truncating category/ activity title in activity view.

---

src/api/__tests__/categories-test.js
src/api/__tests__/parse-test.js
src/api/__tests__/sync-test.js
src/api/categories.js
src/api/parse.js
src/api/sync.js
src/constants/actions.js
src/containers/ActivityContainer.js
src/views/CategoryList/index.js

- move category color fallbacks to api
- fix broken load() api method
- fix bad action creator import for `ActivityContainer`
- update entities on load success

Activity section fixes

---

scripts/helpers.js
src/components/Event/__tests__/Event-tests.js
src/components/Event/index.js
src/containers/__tests__/MilestoneEventContainer-tests.js
src/containers/__tests__/ScheduledCallEventContainer-tests.js
src/views/EventList/__tests__/EventList-tests.js
src/views/EventList/index.js
src/views/ScheduleList/__tests__/__snapshots__/ScheduleList-test.js.snap
src/views/ScheduleListCalendar/__tests__/__snapshots__/ScheduleListCalendar-test.js.snap
src/views/StartCall/__tests__/StartCall-tests.js
src/views/StartCall/__tests__/__snapshots__/StartCall-tests.js.snap

Use iso8601

---

src/__tests__/navigationHelpers-test.js
src/navigationHelpers.js
src/reducers/navigation/__tests__/top-test.js
src/reducers/navigation/top.js

Remove schedule detail route when call is scheduled successfully

---

scripts/jest/environment.js
src/views/ScheduleList/__tests__/__snapshots__/ScheduleList-test.js.snap
src/views/ScheduleListCalendar/__tests__/__snapshots__/ScheduleListCalendar-test.js.snap

Stub date to be fixed in tests

---

scripts/jest/environment.js
src/api/__tests__/callNotes-test.js
src/api/callNotes.js
src/api/index.js
src/api/schemas.js
src/views/ScheduleList/__tests__/__snapshots__/ScheduleList-test.js.snap
src/views/ScheduleListCalendar/__tests__/__snapshots__/ScheduleListCalendar-test.js.snap

Call Notes API

---

android/app/build.gradle
src/containers/ActivationContainer.js
src/containers/LoginContainer.js
src/views/Activation.js
src/views/Login.js
src/views/LoginStatusMessage.js
src/views/__tests__/Activation-test.js
src/views/__tests__/Login-test.js
src/views/__tests__/LoginStatusMessage-test.js
src/views/__tests__/__snapshots__/Activation-test.js.snap
src/views/__tests__/__snapshots__/Login-test.js.snap
src/views/__tests__/__snapshots__/LoginStatusMessage-test.js.snap

Fix login back button

---

src/components/FormView.js
src/components/FormView/index.js
src/components/FormView/styles.js
src/components/Stepper/__tests__/__snapshots__/Stepper-tests.js.snap
src/components/Stepper/index.js
src/components/index.js
src/views/Activation.js
src/views/Login.js
src/views/__tests__/__snapshots__/Activation-test.js.snap
src/views/__tests__/__snapshots__/Login-test.js.snap

Dismiss keyboard

---

src/components/Stepper/__tests__/__snapshots__/Stepper-tests.js.snap
src/components/Stepper/index.js
src/views/OnboardingSaving/index.js

Fix Stepper Component

---

package.json
src/views/ScheduleDetail/__tests__/ScheduleDetail-test.js
src/views/ScheduleDetail/index.js

Schedule Call AM/PM clock

---

android/app/src/main/AndroidManifest.xml

Disable landscape orientation

---

src/actions/__tests__/notifications-test.js
src/actions/notifications.js

Handle data-less notifications

---

src/containers/CameraRollContainer.js
src/views/CameraRoll/__tests__/__snapshots__/index-test.js.snap
src/views/CameraRoll/__tests__/index-test.js
src/views/CameraRoll/index.js
src/views/CameraRoll/styles.js

Fix up Camera Roll view

---

src/views/Activity/__tests__/__snapshots__/Activity-test.js.snap
src/views/Activity/index.js
src/views/Journey/__tests__/Journey-tests.js
src/views/Journey/__tests__/__snapshots__/Journey-tests.js.snap

Remove tint colour from activity icons

---

src/views/ScheduleDetail/index.js

12 hour clock, with AM/ PM instead of 24 hour clock.
@justinvdm ready for review

Fixed schedule detail time formatting

---

scripts/jest/environment.js
src/containers/EventListContainer.js
src/containers/__tests__/EventListContainer-tests.js

Better Event List Grouping

---

src/views/Journey/index.js

Changed Journey Label

---

src/views/ScheduleList/__tests__/__snapshots__/ScheduleList-test.js.snap
src/views/ScheduleList/styles.js

Fix calendar circles being cut off on smaller screens

---

src/views/Activity/__tests__/__snapshots__/Activity-test.js.snap
src/views/Activity/index.js

Copy change on activities page: s/Prompts/Tips

---

src/components/Pagination/__tests__/Pagination-test.js
src/components/Pagination/__tests__/__snapshots__/Pagination-test.js.snap
src/components/Pagination/index.js
src/views/CallNoteSteps/__tests__/__snapshots__/CallNoteSteps-tests.js.snap
src/views/CallNoteSteps/index.js
src/views/FormStep/__tests__/FormStep-tests.js
src/views/FormStep/__tests__/__snapshots__/FormStep-tests.js.snap
src/views/FormStep/index.js

Grey out first pagination button for call notes steps

---

src/components/Event/__tests__/__snapshots__/Event-tests.js.snap
src/components/Event/index.js
src/components/Event/styles.js
src/containers/CallNoteEventContainer.js
src/containers/__tests__/CallNoteEventContainer-test.js
src/containers/events.js
src/views/CallNoteEvent/__tests__/CallNoteEvent-test.js
src/views/CallNoteEvent/index.js

Add call completed event

---

src/views/ScheduleList/__tests__/__snapshots__/ScheduleList-test.js.snap
src/views/ScheduleList/styles.js
src/views/ScheduleListCalendar/__tests__/__snapshots__/ScheduleListCalendar-test.js.snap
src/views/ScheduleListCalendar/styles.js

Fix calendar view on smaller screens

---

src/views/CallNoteSteps/__tests__/__snapshots__/CallNoteSteps-tests.js.snap
src/views/CallNoteSteps/index.js
src/views/CallNoteSteps/styles.js
src/views/FormStep/styles.js

Respond to smaller screen sizes better for call note mood step

---

src/views/CallCompleted/__tests__/__snapshots__/CallCompleted-test.js.snap
src/views/CallCompleted/styles.js
src/views/CallNoteSaved/__tests__/__snapshots__/CallNoteSaved-test.js.snap
src/views/CallNoteSaved/index.js
src/views/CallNoteSaved/styles.js

Fix completed views on smaller screens

---

src/views/Landing/__tests__/__snapshots__/index-test.js.snap
src/views/Landing/index.js

@smn @Mitso @projectmushroom tiny PR, ready for review

Copy change for landing page

---

src/components/Event/index.js

Allow event blurbs to span 2 lines

---

src/constants/callNote.js
src/views/CallNoteDetail/index.js
src/views/CallNoteSteps/index.js

@codiebeulaine could you review this? Think you'd have the most context

Use programmatic call note values

---

src/components/Stepper/__tests__/Stepper-tests.js
src/components/Stepper/__tests__/__snapshots__/Stepper-tests.js.snap
src/components/Stepper/index.js

Change Stepper to transition the same as the rest of the app

---

package.json
src/views/CategoryAbout/__tests__/__snapshots__/CategoryAbout-test.js.snap
src/views/CategoryAbout/styles.js

@smn @Mitso @projectmushroom tiny PR, ready for review

10 dp padding for Category image

---

src/__tests__/navigationHelpers-test.js
src/navigationHelpers.js
src/reducers/navigation/__tests__/top-test.js

Remove dummy route workaround for remove() nav helper

---

.npmrc
README.md
package.json
utils/dev-release.sh
utils/version.sh

We are soon going to need to do dev releases (for the next feature to be deployed) and hotfix releases (for fixes to the currently live version of the app). `git flow release` can't help us for dev releases, since it merges changes from develop into master (we plan on using `master` as the stable branch for the live version of the app).
Since we need to diverge a bit from git flow, we should document how this new process will look.
@smn ready for review

Document release process

---

src/components/PatternBackground/__tests__/PatternBackground-tests.js
src/components/PatternBackground/__tests__/__snapshots__/PatternBackground-tests.js.snap
src/components/PatternBackground/index.js
src/components/PatternBackground/styles.js
src/views/Journey/__tests__/__snapshots__/Journey-tests.js.snap

Fix PatternBackground when content is shorter than pattern image

---

scripts/fixtures.js
scripts/helpers.js
src/api/__tests__/imageUrl-test.js
src/api/__tests__/parse-test.js
src/api/imageUrl.js
src/api/index.js
src/api/parse.js
src/components/ActivityList/__tests__/ActivityList-test.js
src/components/ActivityList/index.js
src/components/Event/__tests__/Event-tests.js
src/components/MilestoneEvent/__tests__/MilestoneEvent-tests.js
src/components/MilestoneEvent/__tests__/__snapshots__/MilestoneEvent-tests.js.snap
src/components/MilestoneEvent/index.js
src/components/MilestoneEvent/styles.js
src/views/Activity/__tests__/Activity-test.js
src/views/Activity/index.js
src/views/CallNoteDetail/__tests__/CallNoteDetail-tests.js
src/views/CallNoteDetail/__tests__/__snapshots__/CallNoteDetail-tests.js.snap
src/views/CallNoteDetail/index.js
src/views/CategoryAbout/__tests__/CategoryAbout-test.js
src/views/CategoryAbout/__tests__/__snapshots__/CategoryAbout-test.js.snap
src/views/CategoryAbout/index.js
src/views/ScheduledCallEvent/__tests__/ScheduledCallEvent-test.js
src/views/ScheduledCallEvent/index.js

At the moment we simply ask the api for images, regardless of their size. This has performance implications, and can make the app practically unusable in some situations.

Ask api to resize images to the appropriate dimensions

---

src/api/__tests__/parse-test.js
src/api/__tests__/profiles-test.js
src/api/parse.js
src/api/profiles.js
src/constants/profile.js

Update profile api parsing to be more robust to non-empty string initial values for profile fields

More robust profile field parsing

---

src/views/CameraRoll/__tests__/__snapshots__/index-test.js.snap
src/views/CameraRoll/index.js

Fix CameraRoll scrolling

---

src/reducers/__tests__/auth-test.js
src/reducers/__tests__/callNotes-test.js
src/reducers/__tests__/entities-test.js
src/reducers/__tests__/onboarding-test.js
src/reducers/auth.js
src/reducers/callNotes.js
src/reducers/entities.js
src/reducers/onboarding.js

Reset state that can be reset on logout

---

src/api/__tests__/parse-test.js
src/api/parse.js

Preserve ordering of entities retrieved from api

---

src/components/Button/index.js

Dismiss keyboard on button press

---

src/views/Onboarding/Inspiration/__tests__/__snapshots__/Inspiration-test.js.snap
src/views/Onboarding/Inspiration/index.js
src/views/Onboarding/ThreeWords/__tests__/__snapshots__/ThreeWords-test.js.snap
src/views/Onboarding/ThreeWords/index.js

Only use multiline text input for steps that need it for Onboarding

---

src/reducers/__tests__/entities-test.js
src/reducers/entities.js

Mark activity complete when a call note is added and its objective is achieved

---

src/views/Onboarding/ThreeWords/__tests__/ThreeWords-test.js
src/views/Onboarding/ThreeWords/__tests__/__snapshots__/ThreeWords-test.js.snap
src/views/Onboarding/ThreeWords/index.js

- Copy changes to example
- More robust word parsing

More intuitive onboarding three words screen

---

src/api/__tests__/richText-test.js
src/api/richText.js
src/components/RichText/Image.js
src/components/RichText/__tests__/RichText-test.js
src/components/RichText/__tests__/__snapshots__/RichText-test.js.snap
src/components/RichText/rules.js
src/components/RichText/styles.js

Add rule for drawing rich text images

---

src/components/RichText/__tests__/RichText-test.js
src/components/RichText/__tests__/__snapshots__/RichText-test.js.snap
src/components/RichText/styles.js

Fix rich text strikethrough

---

src/components/NavTabBar/__tests__/__snapshots__/NavTabBar-test.js.snap
src/components/NavTabBar/index.js

Blogs was the next in-development feature. We are putting it on hold because of a change in project direction. We still want to use the `develop` branch for in-development features though, so the plan is to just not surface this feature in the UI for now.

Hide blog nav tab

---

scripts/helpers.js
src/containers/CategoryContainer.js
src/containers/CategoryListContainer.js
src/containers/ScheduledCallActivityContainer.js
src/containers/ScheduledCallCategoryContainer.js
src/containers/__tests__/ScheduledCallActivityContainer-test.js
src/containers/__tests__/ScheduledCallCategoryContainer-test.js
src/store/__tests__/helpers-test.js
src/store/helpers.js

We show hidden categories and activities when adding an activity to a scheduled call.

Don't show hidden categories and activities

---

src/components/ControlledStepper/__tests__/ControlledStepper-tests.js
src/components/ControlledStepper/__tests__/__snapshots__/ControlledStepper-tests.js.snap
src/components/ControlledStepper/index.js
src/components/FormStep/index.js
src/components/index.js

At the moment we have a stepper that does the navigation between steps itself. This isn't enough for call notes v2, where there is more complex logic dictating which step one sees next.
We need a new component that just takes in navigation state and draws the right thing, so that we can do the navigation logic for more complex use cases like this inside a reducer.

Add a ControlledStepper component

---

src/containers/CallNoteStepsContainer.js
src/views/CallNoteSteps/Reflections/__tests__/Reflections-test.js
src/views/CallNoteSteps/Reflections/__tests__/__snapshots__/Reflections-test.js.snap
src/views/CallNoteSteps/Reflections/index.js

Enable back button functionality for reflections screen

---

src/constants/callNotes.js
src/views/CallNoteStepsV2/ActivityProgress/__tests__/__snapshots__/ActivityProgress-test.js.snap
src/views/CallNoteStepsV2/ActivityProgress/index.js
src/views/CallNoteStepsV2/CallQuality/__tests__/CallQuality-test.js

Fixes to get call notes v2 working with api

---

src/views/CallNoteStepsV2/ActivityProgress/__tests__/ActivityProgress-test.js
src/views/CallNoteStepsV2/ActivityProgress/index.js

@nathanbegbie depends on #361 otherwise ready for review

Scroll to top for activity progress when activity changes

---

src/containers/ActivityContainer.js
src/containers/__tests__/ActivityContainer-test.js
src/store/__tests__/helpers-test.js
src/store/helpers.js
src/views/Activity/__tests__/Activity-test.js
src/views/Activity/__tests__/__snapshots__/Activity-test.js.snap
src/views/Activity/index.js
src/views/CallNoteStepsV2/CallResult/__tests__/CallResult-test.js
src/views/CallNoteStepsV2/CallResult/index.js
src/views/CallNoteStepsV2/__tests__/CallNoteStepsV2-test.js
src/views/CallNoteStepsV2/index.js

Call note v2 fixes

---

src/components/NavigationStack/__tests__/NavigationStack-test.js
src/components/NavigationStack/index.js

Fix navigation stack to still render even if routes hasnt changed

---

scripts/helpers.js
src/api/__tests__/callNotes-test.js
src/api/__tests__/parse-test.js
src/api/callNotes.js
src/api/parse.js
src/api/schemas.js

Parse and use activityData property returned from call note api methods

---

android/build.gradle

See: https://github.com/facebook/react-native/issues/14223 and https://github.com/facebook/react-native/issues/14225

Update build.gradle to determine correct dependencies
