package.json, src/components/Label/__tests__/Label-test.js, src/components/Label/__tests__/__snapshots__/Label-test.js.snap
We'd like to use this feature for testing that our components render their given properties according to what we've visually confirmed (and continue to as the codebase changes over time).
The plan is to require PRs with components and snapshot tests to have corresponding screenshots of the cases we are testing, to ensure that we have in fact visually confirmed that these cases are working as expected.
=> Use jest's toMatchSnapshot()

src/stores/__tests__/helpers-test.js, src/stores/configureStore.js, src/stores/initialState.js
I was initially thinking that `initialState()` would be a sensible place to define the initial values, but the defining the initial state in each reducer makes more sense.
=> Remove unnecessary initialState() function

src/constants/actions.js, src/reducers/__tests__/test-entities.js, src/reducers/entities.js, src/reducers/index.js, src/stores/configureStore.js
At the moment we do this a bit implicitly by inspecting for an `entity` property in the action's payload.
Something like this seems a bit more explicit:
```js
// src/constants.js
const { PROFILE_FETCH_SUCCESS } from 'src/profile/constants';
const ENTITY_ACTIONS = [
PROFILE_FETCH_SUCCESS,
];
// src/entitites/reducer.js
const reduceEntities = (state, action)) => includes(ENTITY_ACTIONS, action.type)
 ? merge(state, action.payload.entities)
 : state;
```
=> Change entity reducer to use a defined set of 'entity actions'

package.json, src/api/__tests__/request-test.js, src/api/request.js
So we don't have snakecase in our camelcase.
=> Normalize case for api requests and responses

src/actions/__tests__/tick-test.js, src/actions/tick.js, src/app.js, src/constants/tick.js, src/reducers/__tests__/tick-test.js, src/reducers/index.js, src/reducers/tick.js
As of #217, the journey screen's top bar renders a next scheduled call reminder, but switches to show "start call now" (where tapping would allow the user to start the call) if the current time is 1 hour or less before or after the most recent sheduled call time.
We need a way for this bar to update when it should switch to its "start call now" mode.
The plan is to dispatch a tick action every minute, and use this for updating the Journey view. Problem is, react-redux won't simply re-render if an action has been dispatched, since the app's state hasn't changed at all (it seems to do a shallow comparison between the new and old state).
These are the approaches I could think of to work around this:
1. in a reducer, record the current time each tick and add it to the state
2. move the logic …
=> Check for journey screen's top bar updates every min

src/views/CallNoteSaving/index.js
This is a workaround, longer term plan is to avoid the current approach of using a callback inside of `componentDidMount()` for saving call notes.
=> Fix duplicate call notes

src/actions/__tests__/callNote-test.js, src/actions/callNote.js, src/reducers/__tests__/callNote-test.js, src/reducers/callNote.js
It seems we still have a duplicate call notes issue. This is still a workaround, but prevents duplicate call notes since this is a change at the action layer, rather than the view layer.
Fixing this properly involves quite a bit of refactoring and cleanup, of which #246 is the start, but we need this fixed sooner than that.
=> Prevent duplicate call notes

src/containers/ScheduledCallEventContainer.js, src/containers/__tests__/ScheduledCallEventContainer-tests.js, src/views/ScheduledCallEvent/__tests__/ScheduledCallEvent-test.js, src/views/ScheduledCallEvent/__tests__/__snapshots__/ScheduledCallEvent-test.js.snap, src/views/ScheduledCallEvent/index.js
At the moment the view details are in the container, we should move these into a view so that the container is only providing the relevant data.
=> Scheduled call event view

android/app/build.gradle, android/build.gradle
This will allow us to publish dev releases. The suffixes still can't be taken into account when calculating the version code google play uses, but provided we arent using suffixes outside of development releases, I think this is fine.
@smn ready for review
=> Allow version suffixes when reading package.json version in build.gradle

scripts/helpers.js, src/api/parse.js, src/store/__tests__/helpers-test.js, src/store/helpers.js
At the moment we rely on the ordering in which categories and activities are given by the api. This isn't the same as the ordering in which the items are arranged in wagtail
If no ordinal field is present, we rely on the ordering the api gives us when listing things.
=> Fix Activity ordering

src/actions/__tests__/schedule-test.js, src/actions/schedule.js, src/containers/ScheduleDetailContainer.js, src/containers/ScheduledCallActivityContainer.js, src/containers/ScheduledCallCategoryContainer.js, src/containers/__tests__/ScheduleDetailContainer-test.js, src/containers/__tests__/ScheduledCallActivityContainer-test.js, src/containers/__tests__/ScheduledCallCategoryContainer-test.js, src/reducers/navigation/__tests__/schedule-test.js, src/reducers/navigation/schedule.js, src/views/ScheduleDetail/__tests__/ScheduleDetail-test.js, src/views/ScheduleDetail/index.js
This happens because the view re-renders, but no longer has the relevant time as state. Our options were to change ourn navigation stack to render all views, even if they aren't currently shown, hold onto the current schedule call state in redux while we are busy choosing an activity, or pass along the currently chosen date and time as context while choosing an activity. Option 3 seemed the most sane solution for what we have at the moment.
=> Schedule call time disappears when an activity is chosen

scripts/helpers.js, src/actions/__tests__/navigation-test.js, src/actions/navigation.js, src/app.js, src/components/Overlay/Loading/__tests__/__snapshots__/Loading-test.js.snap, src/components/Overlay/Loading/index.js, src/components/Stepper/__tests__/Stepper-tests.js, src/components/Stepper/index.js, src/store/__tests__/helpers-test.js, src/store/helpers.js
This PR adds the following behaviour when device back button is pressed:
- if on landing screen, exit app
- else if on a 'main' page (not overlays are showing), logout
- else if not in a stepper, dismiss the current overlay
- else if in a stepper (onboarding, call notes)
- if not at step 0, go back a step
- else revert to steps above
=> Functional device back button

src/components/NavigationStack/__tests__/__snapshots__/NavigationStack-test.js.snap, src/components/NavigationStack/index.js, src/components/Stepper/__tests__/__snapshots__/Stepper-tests.js.snap
Turns out that this was a [reconciliation](https://facebook.github.io/react/docs/reconciliation.html) issue in `NavigationStack`. When a change happened somewhere, we would re-render the navigation stack. If the active route didn't change, it would render a single route rather than left and right "slides" to transition between. It seems that this change caused the react component to be re-mounted and rendered.
To fix this, we don't change the transition state if the active route has not changed.
=> Fix keyboard disappearing after first character

src/components/RichText/__tests__/RichText-test.js, src/components/RichText/__tests__/__snapshots__/RichText-test.js.snap, src/components/RichText/index.js, src/components/RichText/rules.js, src/components/RichText/styles.js, src/components/index.js
This adds a `RichText` component that uses the syntax trees returned by `richText()` (adding in #312) as input.
See #312's description for some context on the approach taken for `RichText`'s implementation.
Styling to come in separate PRs.
=> Basics for RichText component

src/effects.js
At the moment we poll for new events to update the journey screen, and fetch recent events creating a new thing via the api if we know that an event would be created as a side effect. Call notes is one of those things, except we still need to set things up to fetch recent events when call notes are created.
=> Fetch recent events on call note create success

src/api/__tests__/richText-test.js, src/api/richText.js, src/components/RichText/styles.js
Now that we are able to draw these fields, there were a few minor differences between the syntax trees we create via our rich text components, and the ones created via simple-markdown.
@Mitso @nathanbegbie depends on #316, otherwise ready for review
=> Fixes for non-markdown rich text fields

src/components/RichText/__tests__/RichText-test.js, src/components/RichText/__tests__/__snapshots__/RichText-test.js.snap, src/components/RichText/rules.js, src/components/RichText/styles.js, src/constants/colors.js
Very unlikely this will be used, but at the moment it just breaks. We should at least show something, rather than have the app break.
Inline code obviously needs some padding, but [this isn't possible](https://github.com/facebook/react-native/issues/3233) for react native `Text` yet, and we don't have the luxury of being able to wrap code in a `View` for this case, since the tree for inline code ends up being nested inside a `Text` element (`View` elements cannot be nested inside `Text`s, at least not yet).
=> Support code in rich text

src/components/NavigationStack/__tests__/NavigationStack-test.js, src/components/NavigationStack/index.js, src/components/Stepper/__tests__/__snapshots__/Stepper-tests.js.snap
At the moment, `NavigationStack` (the component responsible for transitioning between routes) only renders the view if it is being transitioned to or from. This means that we lose view state for all other routes on the stack that are not being shown.
To fix this, we should still render the hidden views, except not actually display them.
=> Navigation stack throws away old routes' view state

src/views/Onboarding/ThreeWords/__tests__/ThreeWords-test.js, src/views/Onboarding/ThreeWords/index.js
For e.g. `foo,bar,` would count as words `['foo', 'bar', '']`, when it should be `['foo', 'bar']`.
=> "Three words" onboarding screen allows empty strings as words

src/components/Section/__tests__/__snapshots__/Section-test.js.snap, src/components/Section/styles.js, src/components/Text/__tests__/__snapshots__/Test-test.js.snap, src/components/Text/styles.js, src/views/Activity/__tests__/__snapshots__/Activity-test.js.snap, src/views/Activity/styles.js, src/views/CallNoteDetail/__tests__/__snapshots__/CallNoteDetail-tests.js.snap, src/views/CallNoteDetail/index.js, src/views/CallNoteDetail/styles.js, src/views/CallNoteSteps/Completed/__tests__/__snapshots__/Completed-test.js.snap, src/views/CategoryAbout/__tests__/__snapshots__/CategoryAbout-test.js.snap
At the moment, if the content for "discussion with activity" section is long enough, it trails off the screen instead of wrapping.
Ended up including some adjustment and alignment fixes for the same screen, which had some implications for other screens using the same styles.
=> Fix text wrapping for call note detail view

.gitignore, README.md, index.android.js, src/config/base.js, src/config/dev.example.js
When building a view it is often useful to render it in isolation rather than navigate to it after every reload. We've been modifying `index.android.js` instead, but this is problematic: it is easy to accidentally commit changes to this file made for testing things in development, for example.
This PR makes that possible by adding a config option. If `USE_DEV_APP` is set to `true` (which can be configured in `src/config/dev.js`), and we are in development mode (`__DEV__ === true`), this will use `src/app.dev.js` as the entry point for the app instead of `src/app.js`.
If one just wanted to add some side effects for testing something in development, this would also be possible: `src/app.dev` would simply need to export `src/app.js`'s default as its default.
=> Add dev entry point

src/components/Pagination/__tests__/Pagination-test.js, src/components/Pagination/__tests__/__snapshots__/Pagination-test.js.snap, src/components/Pagination/index.js, src/components/Stepper/index.js, src/constants/behavior.js
This prevents users from moving further ahead in the stepper than they should because of tapping the next button multiple times.
@nathanbebgie ready for review
=> Debounce form steps
